"""add playlist index to download jobs

Revision ID: 89cc0988d52b
Revises: 7ec0cb2b7cfd
Create Date: 2026-08-25 14:59:59.706046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cc0988d52b'
down_revision: Union[str, None] = '7ec0cb2b7cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_jobs', sa.Column('playlist_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_jobs', 'playlist_index')
    # ### end Alembic commands ###
