"""add payments and plan unlimited flag

Revision ID: d87710fec995
Revises: 89cc0988d52b
Create Date: 2026-08-30 20:39:41.670749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87710fec995'
down_revision: Union[str, None] = '89cc0988d52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentstatus'), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=512), nullable=False),
    sa.Column('receipt_file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_file_type', sa.String(length=32), nullable=False),
    sa.Column('user_receipt_message_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_message_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('plans', sa.Column('is_unlimited', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('plans', 'is_unlimited', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'is_unlimited')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_table('payments')
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentstatus').drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
